name: Deploy Application

on:
  push:
    branches:
      - main  # Cabang yang digunakan untuk trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Versi Node.js yang digunakan

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          sudo apt-get install -y openssh-client
          echo "${SSH_PRIVATE_KEY}" | ssh-add -
          rsync -avz --delete ./dist/ user@server:/path/to/deploy/
          ssh user@server 'pm2 restart app'

